config/routes.rb
Rails.application.routes.draw do
  
  root to: "customers#index"
  get '/customers/approve' => 'customers#approve'
  resources :customers
  mount API::Base, at: "/"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord

    validates :customerFirstName, presence: true
    validates :customerLastName, presence: true

    validates :customerEmail, presence: true
    validates :customerEmail, format: { with: URI::MailTo::EMAIL_REGEXP } 

    validates :customerPhone, presence: true
    validates :customerPhone, length: { minimum: 10, maximum: 10 }
    validates :customerPhone, numericality: { only_integer: true }

    validates :businessName, presence: true 
    validates :businessLogo, presence: true
    validates :businessTrn, presence: true
    validates :businessEmail, presence: true
    validates :businessEmail, format: { with: URI::MailTo::EMAIL_REGEXP } 

    validates :businessPhone, presence: true
    validates :businessPhone, length: { minimum: 10, maximum: 10 }
    validates :businessPhone, numericality: { only_integer: true }
    
    validates :street, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :zipcode, presence: true
    validates :country, presence: true



    
    has_one_attached :businessLogo

    validate :image_type

    private

    def image_type
        if businessLogo.attached? == false
            errors.add(:'business Logo', "is missing!")
        end
        if businessLogo.attached? != false
            if !businessLogo.content_type.in?(%('image/jpeg image/png image/jpg'))
                errors.add(:'business Logo', "needs to be a jpeg, jpg or png!")
            end
        end
        
    end

    default_scope { order(created_at: :desc) }
    
end

app/models/firm.rb
class Firm < ApplicationRecord
    validates :name, presence: true 
    validates :trn, presence: true
    validates :email, presence: true
    validates :phone, presence: true
    validates :address, presence: true

    default_scope { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :first, presence: true 
    validates :last, presence: true
    validates :email, presence: true
    validates :phone, presence: true

    default_scope { order(created_at: :desc) }
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::Base
  end
end

app/controllers/api/v1/base.rb
module API
    module V1
      class Base < Grape::API
        mount API::V1::Customers
      end
    end
  end

app/controllers/api/v1/customers.rb
module API
    module V1
      class Customers < Grape::API
        include API::V1::Defaults
        resource :customers do
          desc "Return all users"
          get "" do
            @customers = Customer.all
          end
        desc "Return a user"
          params do
            requires :id, type: String, desc: "ID of the user"
          end
          get ":id" do
            Customer.where(id: permitted_params[:id]).first!
          end
        end
      end
    end
  end

app/controllers/api/v1/defaults.rb
module API
    module V1
      module Defaults
        extend ActiveSupport::Concern
  
        included do
          prefix "api"
          version "v1", using: :path
          default_format :json
          format :json
          formatter :json, 
               Grape::Formatter::ActiveModelSerializers
  
          helpers do
            def permitted_params
              @permitted_params ||= declared(params, 
                 include_missing: false)
            end
  
            def logger
              Rails.logger
            end
          end
  
          rescue_from ActiveRecord::RecordNotFound do |e|
            error_response(message: e.message, status: 404)
          end
  
          rescue_from ActiveRecord::RecordInvalid do |e|
            error_response(message: e.message, status: 422)
          end
        end
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found 
    
    protected
    def resource_not_found 
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def approve
    @approves = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params) 
    if @customer.save
      flash[:success] = "Application has been added"
      redirect_to customers_path 
    else
      flash.now[:danger] = "Application has not been added"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      flash[:success] = "Application has been updated"
      redirect_to @customer 
    else
      flash.now[:danger] = "Application has not been updated"
      render :edit
    end
  end

  def destroy
    if @customer.destroy
      flash[:success] = "Application has been deleted."
      redirect_to customers_path 
    end
  end

  protected
  def resource_not_found
    message = "The information you are looking for could not be found" 
    flash[:alert] = message
    redirect_to root_path
  end

  private
  def set_customer
    @customer = Customer.find(params[:id])
    end

  def customer_params
  params.require(:customer).permit(:customerFirstName, :customerLastName, :customerPhone, :customerEmail, :businessName, 
    :businessLogo, :businessTrn, :businessEmail, :businessPhone, :street, :city, :state, :zipcode, :country, :status ) 
  end
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  before_action :set_firm, only: [:show, :edit, :update, :destroy]

  def index
    @firms = Firm.all
  end

  def new
    @firm = Firm.new
  end

  def create
    @firm = Firm.new(firm_params) 
    if @firm .save
      flash[:success] = "Infomation has been added"
      redirect_to firms_path 
    else
      flash.now[:danger] = "Infomation has not been added"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @firm.update(firm_params)
      flash[:success] = "Infomation has been updated"
      redirect_to @firm 
    else
      flash.now[:danger] = "Infomation has not been updated"
      render :edit
    end
  end

  def destroy
    if @firm.destroy
      flash[:success] = "Information has been deleted."
      redirect_to firms_path 
    end
  end

  protected
  def resource_not_found
    message = "The information you are looking for could not be found" 
    flash[:alert] = message
    redirect_to root_path
  end

  private
  def set_firm
    @firm  = Firm.find(params[:id])
    end

  def firm_params
  params.require(:firm ).permit(:name, :trn, :phone, :email, :address) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      flash[:success] = "Infomation has been added"
      redirect_to users_path 
    else
      flash.now[:danger] = "Infomation has not been added"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Infomation has been updated"
      redirect_to @user 
    else
      flash.now[:danger] = "Infomation has not been updated"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Information has been deleted."
      redirect_to users_path 
    end
  end

  protected
  def resource_not_found
    message = "The information you are looking for could not be found" 
    flash[:alert] = message
    redirect_to root_path
  end

  private
  def set_user
    @user = User.find(params[:id])
    end

  def user_params
  params.require(:user).permit(:first, :last, :phone, :email) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/firm_helper.rb
module FirmHelper
end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/approve.html.erb
<h2 class='text-center'>Approve Businesses</h2>
<% if @approves.empty? %>
<h1 id="no-articles">No Applications Created</h1>
<% else %>
    <% @approves.each do |customer| %> 
    <% if customer.status!='false' %>
    <div class="well well-lg">
    <div class="article-title"> 
    <%= customer.customerFirstName %>-<%= customer.customerLastName %>
    </div>
    <div class="article-title"> 
    <%= customer.customerPhone %>
    </div>
    <div class="article-title"> 
    <%= customer.customerEmail %>
    </div>
    <div class="article-title"> 
    <%= customer.businessName %>
    </div>
    <h4><%= link_to "See details", customer_path(customer) %><h4>
    </div> 
    <% else %>
    
    <% end %> 
<% end %> 
<% end %>

app/views/customers/edit.html.erb
<h3 class='text-center'>Editing Application</h3>
<div class='row'>
<div class='col-md-12'>
<%= form_for(@customer, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<% if @customer.errors.any? %>
<div class="panel panel-danger col-md-offset-1">
<div class="panel-heading"> 
<h2 class="panel-title">
<%= pluralize(@customer.errors.count, "error") %>
prohibited this application from being saved: </h2>
<div class="panel-body"> 
<ul>
<% @customer.errors.full_messages.each do |msg| %> 
<li>
<%= msg %> 
</li>
<% end %> 
</ul>
</div> 
</div>
</div> 
<% end %>
<div class="text-center">

<%= f.select(:status, :Reject => 'false', :Approve => 'true') %>
</div>
<h4 class='text-center'> Customer Details</h4>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'Customer First Name '%> 
</div>
<div class='col-md-11'>
<%= f.text_field :customerFirstName, class: 'form-control', placeholder: 'Customer first Name', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'customer Last Name' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :customerLastName, class: 'form-control', placeholder: 'Customer last Name', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'customer Email' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :customerEmail, class: 'form-control', placeholder: 'Customer email', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'customer Phone' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :customerPhone, class: 'form-control', placeholder: 'Customer phone Number', autofocus: true %> 
</div>
</div>
<h4 class='text-center'> Business Details</h4>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Name' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :businessName, class: 'form-control', placeholder: 'Business Name', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Logo' %> 
</div>
<div class='col-md-11'>
<%= f.file_field :businessLogo, class: 'form-control', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Trn' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :businessTrn, class: 'form-control', placeholder: 'Business TRN', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Email' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :businessEmail, class: 'form-control', placeholder: 'Business email', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Phone' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :businessPhone, class: 'form-control', placeholder: 'Business Phone', autofocus: true %> 
</div>
</div>
<h4 class='text-center'> Business Address</h4>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'Street' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :street, class: 'form-control', placeholder: 'Street eg 44 main', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'City' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :city, class: 'form-control', placeholder: 'City eg Montego bay', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'State' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :state, class: 'form-control', placeholder: 'State eg st James', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'Zip Code' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :zipcode, class: 'form-control', placeholder: 'Zip code eg 000000', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'Country' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :country, class: 'form-control', placeholder: 'Country eg Jamaica', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='col-md-offset-1 col-md-11'>
<%= f.submit class: 'btn btn-primary btn-lg pull-right' %> 
</div>
</div> 
<% end %>
</div> 
</div>

app/views/customers/index.html.erb
<%= link_to "Create New Application", new_customer_path, class: "btn btn-primary btn-lg pb-3", id: "new-article-btn" %>
<%= link_to "Approve List", '/customers/approve', class: "btn btn-primary btn-lg pb-3", id: "new-article-btn" %>

<% if @customers.empty? %>
<h1 id="no-articles">No Applications Created</h1>
<% else %>
<% @customers.each do |customer| %> 
<div class="well well-lg">
<div class="article-title"> 
<%= customer.customerFirstName %>-<%= customer.customerLastName %>
</div>
<div class="article-title"> 
<%= customer.customerPhone %>
</div>
<div class="article-title"> 
<%= customer.customerEmail %>
</div>
<div class="article-title"> 
<%= customer.businessName %>
</div>
<h4><%= link_to "See details", customer_path(customer) %><h4>
</div> 
<% end %> 
<% end %>

app/views/customers/new.html.erb
<h3 class='text-center'>Creating New Application</h3>
<div class='row'>
<div class='col-md-12'>
<%= form_for(@customer, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<% if @customer.errors.any? %>
<div class="panel panel-danger col-md-offset-1">
<div class="panel-heading"> 
<h2 class="panel-title">
<%= pluralize(@customer.errors.count, "error") %>
prohibited this Application from being saved: </h2>
<div class="panel-body"> 
<ul>
<% @customer.errors.full_messages.each do |msg| %> 
<li>
<%= msg %> 
</li>
<% end %> 
</ul>
</div> 
</div>
</div> 
<% end %>
<h4 class='text-center'> Customer Details</h4>
<div class="text-center " style="display:none"> 
<%= f.select(:status, :Reject => 'false', :Approve => 'true') %>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'Customer First Name '%> 
</div>
<div class='col-md-11'>
<%= f.text_field :customerFirstName, class: 'form-control', placeholder: 'Customer first Name', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'customer Last Name' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :customerLastName, class: 'form-control', placeholder: 'Customer last Name', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'customer Email' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :customerEmail, class: 'form-control', placeholder: 'Customer email', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'customer Phone' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :customerPhone, class: 'form-control', placeholder: 'Customer phone Number', autofocus: true %> 
</div>
</div>
<h4 class='text-center'> Business Details</h4>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Name' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :businessName, class: 'form-control', placeholder: 'Business Name', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Logo' %> 
</div>
<div class='col-md-11'>
<%= f.file_field :businessLogo, class: 'form-control', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Trn' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :businessTrn, class: 'form-control', placeholder: 'Business TRN', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Email' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :businessEmail, class: 'form-control', placeholder: 'Business email', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'business Phone' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :businessPhone, class: 'form-control', placeholder: 'Business Phone', autofocus: true %> 
</div>
</div>

<h4 class='text-center'> Business Address</h4>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'Street' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :street, class: 'form-control', placeholder: 'Street eg 44 main', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'City' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :city, class: 'form-control', placeholder: 'City eg Montego bay', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'State' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :state, class: 'form-control', placeholder: 'State eg st James', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'Zip Code' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :zipcode, class: 'form-control', placeholder: 'Zip code eg 000000', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :'Country' %> 
</div>
<div class='col-md-11'>
<%= f.text_field :country, class: 'form-control', placeholder: 'Country eg Jamaica', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='col-md-offset-1 col-md-11'>
<%= f.submit class: 'btn btn-primary btn-lg pull-right' %> 
</div>
</div> 
<% end %>
</div> 
</div>

app/views/customers/show.html.erb
<article class="detail-article">
<h4 class='text-center'> Customer Details</h4>
<div class="glyphicon glyphicon-calendar" id="article-date"> 
<%= @customer.created_at.strftime("%b %d, %Y") %>
</div>
<h1 class="article-detail-title">Customer Name:
<%= @customer.customerFirstName %>-<%= @customer.customerLastName %>
</h1>
<h2 class="article-detail-title">
Customer Email:
<%= @customer.customerEmail %>
</h2>
<h2 class="article-detail-title">
Customer Phone number:
<%= @customer.customerPhone %>
</h2>
<h4 class='text-center'> Business Details</h4>
<div class='text-center'>
<%= @customer.businessLogo %>
<%= image_tag url_for(@customer.businessLogo) %>

</div>
<h1 class="article-detail-title">
Business Name:
<%= @customer.businessName %>
</h1>
<div class="glyphicon glyphicon-calendar" id="article-date"> 
<%= @customer.created_at.strftime("%b %d, %Y") %>
</div>
<h2 class="article-detail-title">
Business TRN:
<%= @customer.businessTrn %>
</h2>
<h2 class="article-detail-title">
Business Email:
<%= @customer.businessEmail %>
</h2>
<h2 class="article-detail-title">
Business Phone number:
<%= @customer.businessPhone %>
</h2>

<div class="edit-delete">
<%= link_to "Update Approve/Reject", edit_customer_path(@customer), class: "btn btn-primary btn-lg btn-space" %>
<%= link_to "Edit Application", edit_customer_path(@customer), class: "btn btn-primary btn-lg btn-space" %>
<%= link_to "Delete Application", customer_path(@customer),
method: :delete,
data: { confirm: "Are you sure you want to delete application?" }, 
class: "btn btn-primary btn-lg btn-space" %>
</div>
</article>

app/views/firms/edit.html.erb
<h3 class='text-center'>Editing Firm</h3>
<div class='row'>
<div class='col-md-12'>
<%= form_for(@firm, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<% if @firm.errors.any? %>
<div class="panel panel-danger col-md-offset-1">
<div class="panel-heading"> 
<h2 class="panel-title">
<%= pluralize(@firm.errors.count, "error") %>
prohibited this business from being saved: </h2>
<div class="panel-body"> 
<ul>
<% @firm.errors.full_messages.each do |msg| %> 
<li>
<%= msg %> 
</li>
<% end %> 
</ul>
</div> 
</div>
</div> 
<% end %>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :name %> 
</div>
<div class='col-md-11'>
<%= f.text_field :name, class: 'form-control', placeholder: 'Business Name', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :trn %> 
</div>
<div class='col-md-11'>
<%= f.text_field :trn, class: 'form-control', placeholder: 'TRN', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :email %> 
</div>
<div class='col-md-11'>
<%= f.text_field :email, class: 'form-control', placeholder: 'email', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :phone %> 
</div>
<div class='col-md-11'>
<%= f.text_field :phone, class: 'form-control', placeholder: 'Phone Number', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :address %> 
</div>
<div class='col-md-11'>
<%= f.text_field :address, class: 'form-control', placeholder: 'Phone Number', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='col-md-offset-1 col-md-11'>
<%= f.submit class: 'btn btn-primary btn-lg pull-right' %> 
</div>
</div> 
<% end %>
</div> 
</div>

app/views/firms/index.html.erb
<%= link_to "Create New Firm", new_firm_path, class: "btn btn-primary btn-lg", id: "new-article-btn" %>
<%= link_to 'Access User section', users_path, class: "btn btn-primary btn-lg" %>
<% if @firms.empty? %>
<h1 id="no-articles">No Firms Created</h1>
<% else %>
<% @firms.each do |firm| %> 
<div class="well well-lg">
<div class="article-title"> 
<%= link_to firm.name, firm_path(firm) %>
</div>
<div class="article-title"> 
<%= firm.trn %>
</div>
<div class="article-title"> 
<%= firm.email %>
</div>
<div class="article-title"> 
<%= firm.phone %>
</div>
<div class="article-title"> 
<%= firm.address %>
</div>
</div> 
<% end %> 
<% end %>

app/views/firms/new.html.erb
<h3 class='text-center'>Creating New Firm</h3>
<div class='row'>
<div class='col-md-12'>
<%= form_for(@firm, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<% if @firm.errors.any? %>
<div class="panel panel-danger col-md-offset-1">
<div class="panel-heading"> 
<h2 class="panel-title">
<%= pluralize(@firm.errors.count, "error") %>
prohibited this business from being saved: </h2>
<div class="panel-body"> 
<ul>
<% @firm.errors.full_messages.each do |msg| %> 
<li>
<%= msg %> 
</li>
<% end %> 
</ul>
</div> 
</div>
</div> 
<% end %>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :name %> 
</div>
<div class='col-md-11'>
<%= f.text_field :name, class: 'form-control', placeholder: 'Business Name', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :trn %> 
</div>
<div class='col-md-11'>
<%= f.text_field :trn, class: 'form-control', placeholder: 'TRN', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :email %> 
</div>
<div class='col-md-11'>
<%= f.text_field :email, class: 'form-control', placeholder: 'email', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :phone %> 
</div>
<div class='col-md-11'>
<%= f.text_field :phone, class: 'form-control', placeholder: 'Phone Number', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :address %> 
</div>
<div class='col-md-11'>
<%= f.text_field :address, class: 'form-control', placeholder: 'Phone Number', autofocus: true %> 
</div>
</div>
<div class='form-group'>
<div class='col-md-offset-1 col-md-11'>
<%= f.submit class: 'btn btn-primary btn-lg pull-right' %> 
</div>
</div> 
<% end %>
</div> 
</div>

app/views/firms/show.html.erb
<article class="detail-article">
<h1 class="article-detail-title">
<%= @firm.name %>
</h1>
<div class="glyphicon glyphicon-calendar" id="article-date"> 
<%= @firm.created_at.strftime("%b %d, %Y") %>
</div>
<h2 class="article-detail-title">
<%= @firm.trn %>
</h2>
<h2 class="article-detail-title">
<%= @firm.phone %>
</h2>
<h2 class="article-detail-title">
<%= @firm.email %>
</h2>
<h2 class="article-detail-title">
<%= @firm.address %>
</h2>
<div class="edit-delete">
<%= link_to "Edit Firm", edit_firm_path(@firm), class: "btn btn-primary btn-lg btn-space" %>
<%= link_to "Delete Firm", firm_path(@firm),
method: :delete,
data: { confirm: "Are you sure you want to delete article?" }, 
class: "btn btn-primary btn-lg btn-space" %>
</div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Applications</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header role="banner">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container-fluid"> 
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse"
data-target="#bs-example-navbar-collapse-1"> 
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to "One Great Studio", root_path, class: "navbar-brand" %> 
</div>
<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav">

</ul> 
</div>
</div> 
</nav>
</header>
<div class="container"> 
<div class="row">
<div class="col-md-12">
<% flash.each do |key, message| %>
<div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
<%= message %> 
</div>
<% end %>
<%= yield %> 
</div>
</div> 
</div>
  </body>
</html>